"""Every number used in either session, from one command.

Nothing here calls a model. If a figure in a deck cannot be produced by this
script from the stored traces and verdicts, it does not go in the deck.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from core.contracts import HARNESS_FAILURES, OUTCOMES
from core.trace import VERDICTS, iter_all, read_verdicts
from metrics import aggregate, cost, judges
from runner.outcomes import tally

ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "reports"
B, DIM, R, Y = "\033[1m", "\033[2m", "\033[0m", "\033[33m"


def h(title: str) -> None:
    print(f"\n{B}{title}{R}\n{DIM}{'-' * len(title)}{R}")


def main() -> int:
    ap = argparse.ArgumentParser(description="Emit every workshop number.")
    ap.add_argument("--k", type=int, default=8)
    ap.add_argument("--json", action="store_true", help="also write reports/report.json")
    a = ap.parse_args()

    headers, rollouts = {}, []
    for hd, r in iter_all():
        headers[r.solver_config] = hd
        rollouts.append(r)
    if not rollouts:
        print("no traces — run scripts/run.py first", file=sys.stderr)
        return 1

    op = VERDICTS / "outcomes.json"
    if not op.exists():
        print("no grades — run scripts/grade.py first", file=sys.stderr)
        return 1
    graded = json.loads(op.read_text())
    outcomes = {tuple(k.split("|")[:2] + [int(k.split("|")[2])]): v
                for k, v in graded["outcomes"].items()}

    am = read_verdicts("answer_match")
    pj = read_verdicts("process_judge")
    mc = read_verdicts("masked_cont")
    tr = read_verdicts("tool_replay")

    simulated = any(hd.get("simulated") for hd in headers.values())
    report: dict = {"simulated": simulated, "k": a.k}

    print()
    if simulated:
        print(f"{Y}{'=' * 78}{R}")
        print(f"{Y}  SIMULATED CORPUS — generated by agent.providers.MockSolver.{R}")
        print(f"{Y}  No provider was called. These are NOT measurements of any real model.{R}")
        print(f"{Y}  Re-run without --mock to produce figures that can be quoted.{R}")
        print(f"{Y}{'=' * 78}{R}")

    h("Pinned configuration")
    for cfg in sorted(headers):
        hd = headers[cfg]
        print(f"  {cfg:11s} model={hd.get('model')}  temp={hd.get('temperature')}  "
              f"prompt={hd.get('prompt_sha')}  config_hash={B}{hd.get('config_hash')}{R}")

    # ---- outcomes -------------------------------------------------------
    h("Outcomes per solver  (seven, not two)")
    ungraded = [r for r in rollouts
                if (r.solver_config, r.task_id, r.run_idx) not in outcomes]
    if ungraded:
        print(f"\n{Y}  {len(ungraded)} rollout(s) on disk have not been graded and are "
              f"excluded below.{R}")
        print(f"{DIM}  Re-run scripts/grade.py to include them.{R}")
        rollouts = [r for r in rollouts if r not in ungraded]

    by_cfg_outcomes = defaultdict(list)
    for r in rollouts:
        by_cfg_outcomes[r.solver_config].append(outcomes[(r.solver_config, r.task_id, r.run_idx)])
    print(f"  {'':11s}" + "".join(f"{o[:9]:>10s}" for o in OUTCOMES) + f"{'err rate':>11s}")
    report["outcomes"] = {}
    for cfg in sorted(by_cfg_outcomes):
        t = tally(by_cfg_outcomes[cfg])
        report["outcomes"][cfg] = t
        print(f"  {cfg:11s}" + "".join(f"{t['counts'][o]:>10d}" for o in OUTCOMES)
              + f"{t['error_rate']:>10.1%}")
    print(f"  {DIM}error rate = ({' + '.join(HARNESS_FAILURES)}) / all rollouts. "
          f"Errored rollouts ARE in the pass@k denominator below.{R}")

    # ---- reliability ----------------------------------------------------
    h(f"Reliability per solver  (k={a.k}, errored rollouts in the denominator)")
    report["reliability"] = {}
    print(f"  {'':11s}{'pass@1':>9s}{'95% CI':>16s}{'pass@k':>9s}{'pass^k':>9s}"
          f"{'maj@k':>9s}{'tasks':>7s}")
    for cfg in sorted(by_cfg_outcomes):
        by_task: dict[str, list[bool]] = defaultdict(list)
        answers_by_task: dict[str, list] = defaultdict(list)
        for r in rollouts:
            if r.solver_config != cfg:
                continue
            ok = outcomes[(cfg, r.task_id, r.run_idx)] == "correct"
            by_task[r.task_id].append(ok)
            answers_by_task[r.task_id].append(str(r.final))
        s = aggregate.summarise(dict(by_task), k=a.k)
        keys = {v.task_id: v.detail.get("key") for v in am}
        maj = [aggregate.majority_at_k(answers_by_task[t], str(keys.get(t)), min(a.k, len(answers_by_task[t])))
               for t in by_task]
        s["majority_at_k"] = sum(maj) / len(maj) if maj else 0.0
        report["reliability"][cfg] = s
        lo, hi = s["pass_1_ci"]
        print(f"  {cfg:11s}{s['pass_1']:>9.3f}{f'[{lo:.2f}, {hi:.2f}]':>16s}"
              f"{s[f'pass_at_{a.k}']:>9.3f}{s[f'pass_hat_{a.k}']:>9.3f}"
              f"{s['majority_at_k']:>9.3f}{s['tasks']:>7d}")
    print(f"  {DIM}pass@k rises with k and flatters everything. pass^k is the "
          f"reliability number.{R}")

    # ---- reasoning effort ----------------------------------------------
    from core.config import EFFORTS, base_config, effort_of

    arms = defaultdict(dict)
    for r in rollouts:
        e = effort_of(r.solver_config)
        if e:
            arms[base_config(r.solver_config)].setdefault(e, []).append(r)
    if arms:
        h("Reasoning effort  (same solver, same tasks, effort is the only change)")
        print(f"  {'':16s}{'n':>5s}{'acc':>8s}{'err':>7s}{'tok out':>10s}"
              f"{'$/run':>10s}{'$/solve':>10s}")
        report["effort"] = {}
        for base in sorted(arms):
            best, worst = None, None
            for e in EFFORTS:
                rs = arms[base].get(e)
                if not rs:
                    continue
                keys = [(r.solver_config, r.task_id, r.run_idx) for r in rs]
                outs = [outcomes[k] for k in keys]
                n = len(rs)
                acc = sum(o == "correct" for o in outs) / n
                err = sum(o in HARNESS_FAILURES for o in outs) / n
                tok = sum(int(r.usage.get("tokens_out", 0)) for r in rs) / n
                usd = sum(float(r.usage.get("usd", 0.0)) for r in rs)
                nc = sum(o == "correct" for o in outs)
                psolve = (usd / nc) if nc else float("inf")
                report["effort"].setdefault(base, {})[e] = {
                    "n": n, "acc": acc, "err": err, "tokens_out": tok,
                    "usd_per_run": usd / n, "usd_per_solve": psolve}
                ps = "inf" if psolve == float("inf") else f"{psolve:.4f}"
                print(f"  {base + '@' + e:16s}{n:>5d}{acc:>8.3f}{err:>7.1%}"
                      f"{tok:>10.0f}{usd / n:>10.4f}{ps:>10s}")
                if best is None or acc > best[1]:
                    best = (e, acc)
                if worst is None or acc < worst[1]:
                    worst = (e, acc)
            if best and worst and best[0] != worst[0]:
                print(f"  {DIM}best {best[0]} ({best[1]:.3f}) vs worst {worst[0]} "
                      f"({worst[1]:.3f}) — more effort is a hypothesis, not a guarantee{R}")
        print(f"  {DIM}Each arm is a separate pinned configuration with its own config_hash. "
              f"Nothing here is averaged across efforts.{R}")

    # ---- deterministic layer -------------------------------------------
    h("Deterministic layer")
    esc = graded["escapes"]
    print(f"  answer_match  escape rate {graded['escape_rate']:.1%}  "
          f"(exact {esc['exact']}  symbolic {esc['symbolic']}  unparsed {esc['unparsed']})")
    trm = sum(1 for v in tr if v.label == "mismatch")
    tool_answered = sum(1 for v in tr if v.detail.get("answer_produced_by_tool"))
    print(f"  tool_replay   {len(tr)} replayed  {trm} mismatch  "
          f"{tool_answered} where a TOOL produced the submitted answer")
    mcm = sum(1 for v in mc if v.label == "mismatch")
    print(f"  masked_cont   {len(mc)} continued  {mcm} landed somewhere other than "
          f"the submission")
    report["deterministic"] = {"escape_rate": graded["escape_rate"], "escapes": esc,
                               "tool_replay_mismatch": trm, "masked_cont_mismatch": mcm,
                               "answer_produced_by_tool": tool_answered}

    # ---- judges ---------------------------------------------------------
    h("Judges")
    ija = judges.inter_judge_agreement(pj)
    print(f"  inter-judge agreement  {ija['raw_agreement']:.1%} raw   "
          f"kappa {ija['cohens_kappa']:.3f}   over {ija['n_pairs']} paired verdicts")
    for c, v in sorted(ija["per_config"].items()):
        print(f"      {c}: {v:.1%}")
    if ija["confusion"]:
        print(f"  {DIM}top disagreements: "
              + ", ".join(f"{x}/{y}×{n}" for (x, y), n in ija["confusion"]) + R)

    sev = judges.severity(pj)
    print("\n  judge severity  (rate of NOT saying ESTABLISHES, across both roles)")
    for j, d in sev.items():
        print(f"      {j:34s} {d['unsound_rate']:>6.1%}  n={d['n']:<4d} "
              f"roles={','.join(d['judging_roles'])}")

    be = judges.blinding_effect(pj)
    print("\n  blinding effect  (same traces, judged both ways)")
    if be.get("n"):
        print(f"      n={be['n']}   verdict change rate {be['change_rate']:.1%}")
        print(f"      unsound when BLINDED   {be['blinded_unsound_rate']:.1%}")
        print(f"      unsound when UNBLINDED {be['unblinded_unsound_rate']:.1%}")
        print(f"      net leniency from seeing the outcome: {be['net_leniency']:+.1%}")
    else:
        print("      no ablation verdicts — run grade.py with --ablation N")

    raww = judges.right_answer_wrong_reasoning(am, pj)
    print("\n  right answer, wrong reasoning")
    print(f"      of {raww['n_correct_judged']} correct runs, "
          f"{raww['any_judge_unsound']} ({raww['rate_any']:.1%}) had at least one judge "
          f"call the reasoning unsound; {raww['both_judges_unsound']} "
          f"({raww['rate_both']:.1%}) had both")
    report["judges"] = {"inter_judge": ija, "severity": sev, "blinding_effect": be,
                        "right_answer_wrong_reasoning": raww}

    # ---- calibration ----------------------------------------------------
    h("Calibration against human labels")
    cal = ROOT / "calibration" / "human_labels.jsonl"
    if cal.exists() and cal.stat().st_size:
        labels = {}
        for line in cal.read_text().splitlines():
            if line.strip():
                d = json.loads(line)
                labels[(d["solver_config"], d["task_id"], int(d["run_idx"]))] = d["label"]
        ha = judges.human_agreement(pj, labels)
        print(f"  {ha['n_labelled']} traces labelled by the instructor "
              f"(single-annotator calibration, not an annotation study)")
        for j, d in ha["per_judge"].items():
            print(f"      {j:34s} agrees {d['agreement']:.1%}  n={d['n']}")
        report["calibration"] = ha
    else:
        print(f"  {Y}no labels yet — run scripts/label.py.{R}")
        print(f"  {DIM}Until this exists, every process number above is an assertion "
              f"rather than a calibrated result.{R}")
        report["calibration"] = None

    # ---- cost -----------------------------------------------------------
    h("Cost")
    cs = cost.summarise(rollouts, outcomes)
    print(f"  {'':11s}{'total $':>10s}{'$/run':>10s}{'$/SUCCESSFUL solve':>21s}{'tok in':>10s}"
          f"{'tok out':>10s}")
    for cfg, d in cs.items():
        ps = "inf" if d["usd_per_successful_solve"] == float("inf") else f"{d['usd_per_successful_solve']:.4f}"
        print(f"  {cfg:11s}{d['usd']:>10.4f}{d['usd_per_run']:>10.4f}{ps:>21s}"
              f"{d['tokens_in']:>10d}{d['tokens_out']:>10d}")
    print(f"  {DIM}Cost per run rewards failing cheaply. Cost per successful solve is "
          f"what the capability costs.{R}")
    report["cost"] = cs

    REPORTS.mkdir(exist_ok=True)
    if a.json:
        (REPORTS / "report.json").write_text(json.dumps(report, indent=1, default=str))
        print(f"\n{DIM}wrote {REPORTS / 'report.json'}{R}")
    print()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
