"""Rollout orchestration: n runs, bounded concurrency, backoff, resumption.

Resumption is idempotent on (solver_config, task_id, run_idx). A batch killed
half way through and restarted does not duplicate work and does not lose it,
because the trace file is append-only and already on disk.
"""
from __future__ import annotations

import random
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from agent.loop import run_rollout
from agent.providers import ProviderError, build
from core.config import RunConfig
from core.contracts import Rollout, Task
from core.trace import append_rollout, completed_keys

MAX_ATTEMPTS = 3
BASE_BACKOFF_S = 0.5


def _with_backoff(fn, attempts: int = MAX_ATTEMPTS):
    """Backoff for faults that escape the loop entirely — i.e. we failed to
    obtain a trace at all.

    Note what is deliberately NOT retried here: a provider error or timeout
    that the loop caught. Those are recorded as the outcomes `error` and
    `timeout` and left in the corpus, because silently re-rolling them until
    one succeeds is precisely how a reported accuracy gets inflated. The error
    rate is a result, not a nuisance to be retried away.
    """
    last = None
    for i in range(attempts):
        try:
            return fn()
        except ProviderError as e:
            last = e
            if i == attempts - 1:
                raise
            time.sleep(BASE_BACKOFF_S * (2 ** i) * (1 + random.random() * 0.3))
    raise last  # pragma: no cover


def run_batch(tasks: list[Task], cfg: RunConfig, n: int, *, mock: bool = False,
              answers: dict[str, int] | None = None, concurrency: int = 4,
              root: Path | None = None, resume: bool = True,
              on_result=None) -> list[Rollout]:
    done = completed_keys(root) if resume else set()
    header = dict(cfg.header())
    header["simulated"] = mock
    if mock:
        header["warning"] = "SIMULATED CORPUS - generated by agent.providers.MockSolver"

    jobs = [
        (t, i) for t in tasks for i in range(n)
        if (cfg.solver_config, t.task_id, i) not in done
    ]
    skipped = len(tasks) * n - len(jobs)
    results: list[Rollout] = []

    def one(task: Task, idx: int) -> Rollout:
        if mock:
            provider = build(cfg.model, solver_config=cfg.solver_config,
                             task_id=task.task_id, run_idx=idx,
                             answer=(answers or {})[task.task_id])
        else:
            provider = build(cfg.model)
        return run_rollout(task, cfg, provider, run_idx=idx, seed=idx)

    with ThreadPoolExecutor(max_workers=concurrency) as pool:
        futs = {pool.submit(_with_backoff, lambda t=t, i=i: one(t, i)): (t, i) for t, i in jobs}
        for fut in as_completed(futs):
            task, idx = futs[fut]
            try:
                r = fut.result()
            except Exception as e:  # noqa: BLE001 - record the failure, never drop it
                from core.trace import TraceRecorder
                rec = TraceRecorder(task.task_id, idx, cfg.solver_config, cfg.config_hash, idx)
                rec.emit("error", fault="exhausted", message=f"{type(e).__name__}: {e}")
                r = rec.finish("error", final=None, usd=0.0, turns=0)
            append_rollout(r, header, root)
            results.append(r)
            if on_result:
                on_result(r)

    return results, skipped
